import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { AppProviders } from "@/context/ContextProvider";

export const metadata: Metadata = {
  title: "Social Web App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className="bg-emerald-800 text-white h-screen flex flex-col" >
        <AppProviders>
          <NavBar />
          <main className="flex-grow flex flex-col justify-center items-center py-6">
            {children}
          </main>
          <Footer />
        </AppProviders>
      </body>
    </html>
  );
}
