import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { AppProviders } from "@/context/ContextProvider";

export const metadata: Metadata = {
  title: "Social Web App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-br from-teal-700 to-teal-900 text-white min-h-screen " >
        <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/food.png')] opacity-25"></div>
        <div className="relative z-10 flex flex-col min-h-screen">
            <AppProviders>
              <NavBar />
              <main className="flex-grow flex flex-col justify-center items-center pt-[3.5rem] pb-[3rem]">
              {children}
              </main>
            <Footer />
          </AppProviders>
        </div>
      </body>
    </html>
  );
}
