name: Frontend CI

on:
  push:
    branches: [ "prod" ]
    paths:
      - 'client/**'
  pull_request:
    branches: [ "prod" ]
    paths:
      - 'client/**'

jobs:

  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy via SSH
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=yes ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e

            # Source environment (important for NVM or custom paths)
            export NVM_DIR="\$HOME/.nvm"
            [ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh"
            [ -s "\$NVM_DIR/bash_completion" ] && \. "\$NVM_DIR/bash_completion"

            # Debug (optional, remove once confirmed working)
            echo "Using node: \$(which node)"
            echo "Using npm: \$(which npm)"
            node -v
            npm -v

            cd /home/ercan/socialwebapp/client
            git pull origin prod
            npm install
            npm run build
            sudo systemctl restart socialwebapp_client.service
          EOF

