name: Frontend CI

on:
  push:
    branches: [ "prod" ]
    paths:
      - 'client/**'
  pull_request:
    branches: [ "prod" ]
    paths:
      - 'client/**'

jobs:

  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

